### ISSUE TITLE
A2 Infografía 

### ISSUE THREAD

**Issue by Diegocruz040708** [SistemasTecTlaxiaco/actividad-2-infografia-Diegocruz040708#1]
[Construcción de conocimiento DiegoCC.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-Diegocruz040708/files/9466438/Construccion.de.conocimiento.DiegoCC.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica, has obtenido un 17.8% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
